__title__ = 'apitest_ezgo'
__description__ = 'easy http interface test frame'
__url__ = ''
__version__ = '0.0.6'
__author__ = 'Gawen'
__author_email__ = '502286126@qq.com'
__license__ = 'Apache-2.0'
__copyright__ = 'Copyright 2022 Gawen'